### ISSUE TITLE
Only one component CSS is compiled

### ISSUE THREAD

**Issue by meydjer** [sveltejs/template-webpack#1]
Hey there.

When I create multiple components with scoped styles, only the last component CSS is compiled. For example: https://gist.github.com/meydjer/817afc7be8330eda3ce45a1be026927c

And, if I'm running `webpack-serve --content public --hot`, the last saved component CSS is compiled. For example, if I save Foo.html and manually refresh the browser, only Foo.html style is compiled. Same thing for App.html and Bar.html.

**Comment by Rich-Harris** [comment]
This is related to https://github.com/sveltejs/svelte-loader/issues/56 — will close it in favour of that, and try to get the fix released this weekend!
