### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined while building to production

### ISSUE THREAD

**Issue by MNITD** [sveltejs/template-webpack#10]
When I was trying to build project with `npm run build`, I got following error: 
![image](https://user-images.githubusercontent.com/17023655/46921455-35735e80-d004-11e8-88ac-18b2eb24f62d.png)
 
Error is referring to webpack and webpack-cli, the [issue](https://github.com/webpack/webpack/issues/8082) says it becouse of some build updates and can be fixed by updating to latest version of webpack and webpack-cli 

So after updating with `npm i webpack@latest webpack-cli@latest -D` project is now successfuly building 

Could you please update this dependencies to latest versions?

**Comment by YuriiNskyi** [comment]
+1 to author, I would also suggest to update `svelte-loader` version, to prevent [this bug](https://github.com/sveltejs/template-webpack/issues/5).

**Comment by JordanShurmer** [comment]
PR #11 fixes this

**Comment by JordanShurmer** [comment]
You can fix it in your project locally if you want. Or use the branch that PR #11 is coming from as your degit source.

```
# Update all dependencies
npm install -g npm-check-updates
ncu -u
```

Also should replace the deprecated webpack-serve with webpack-dev-server

```
npm uninstall --save-dev webpack-serve
npm install --save-dev webpack-dev-server
```

Then update the `scripts.dev` script in webpack.json to simply be "webpack-dev-server"
