### ISSUE TITLE
What does "window.app = app;" mean?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/template-webpack#19]
The content of `main.js` in `github.com/sveltejs/template-webpack`:

```js
import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

window.app = app;

export default app;
```

The same file in `github.com/sveltejs/template`:

```js
import App from './App.svelte';

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});

export default app;
```

I'm wondering what difference `window.app = app;` means.

Can you answer please?

**Comment by coussej** [comment]
From the tutorials of previous versions of svelte, I remember this was merely for easy debugging. By doing this, you can access the parent svelte component (app) from the console.

**Comment by s0kil** [comment]
It means that if you go to browser console, and type `app` or `window.app` it will be accessible, you could modify the app, and debug it.

**Comment by antony** [comment]
For usage questions, please come and [chat to us](https://svelte.dev/chat)
