### ISSUE TITLE
Document use of CSS loaders

### ISSUE THREAD

**Issue by ghost** [sveltejs/template-webpack#30]
The template [contains](https://github.com/sveltejs/template-webpack/blob/master/webpack.config.js#L39) the comment "MiniCssExtractPlugin doesn't support HMR. For developing, use 'style-loader' instead." As a newcomer to both Webpack and Svelte, I don't know why I would want to use MiniCssExtractPlugin, so it would be helpful for that part of the configuration to be explained further.

**Comment by benmccann** [comment]
This is fixed now with #36
