### ISSUE TITLE
Hot reload, how to watch for global.css too

### ISSUE THREAD

**Issue by Alexn117** [sveltejs/template-webpack#31]
I'm new to webpack. I opted to use this template, instead of the default one with Rollup, because webpack comes with a proxy feature that I need for development and Rollup currently does not.

The problem is that the `global.css` inside the public folder does not trigger hot reload when changes are made. Making changes to the styles in .svelte files does work as expected. I tested making changes to the same `global.css` in the default template with Rollup and that triggers hot reload just fine. Anyone know which settings I'm supposed to add to `webpack.config.js` to get this to work?

**Comment by non25** [comment]
You need to set `hot: true` in the `devServer` section, and import `global.css` in `main.js` to have hot module replacement of css.
Import it like this:

```javascript
import './global.css';
```
