### ISSUE TITLE
Make this repository a template repository

### ISSUE THREAD

**Issue by MarcusOtter** [sveltejs/template-webpack#44]
This should be a template repository just like https://github.com/sveltejs/template. Here's the setting, right under the repository's name:
[![image](https://user-images.githubusercontent.com/35617441/126914549-8a3f20b1-f5ed-4abf-a76e-a179bd4b60d6.png)](https://github.com/sveltejs/template-webpack/settings)

About template repositories: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-repository-from-a-template

**Comment by Conduitry** [comment]
Huh, I guess this one was missed somehow. It's a template repo now - thanks!
