### ISSUE TITLE
 Error: Can't resolve css file

### ISSUE THREAD

**Issue by philimonov-alexander** [sveltejs/template-webpack#5]
With `emitCss: true` options emited css files are not founded. It seems that the problem is related to  https://github.com/sveltejs/svelte-loader/issues/45 "the CSS is written to a virtual file system"
NodeJs version: 8.11
OS: Windows 10

```
ERROR in ./src/App.html
Module not found: Error: Can't resolve 'C:sveltesrcApp.svelte.css' in 'C:\svelte\src'
 @ ./src/App.html 71:0-38
 @ ./src/main.js
 @ multi ./src/main.js
```

**Comment by thewindsword** [comment]
It look like a path problem on Windows 10，you can see this pr.
https://github.com/sveltejs/svelte-loader/pull/64

if you want to build immediately，open `node_modules\svelte-loader\index.js`
change lines 121: `cssFilepath` to `posixify(cssFilepath)`

**Comment by philimonov-alexander** [comment]
Thanks,  https://github.com/sveltejs/svelte-loader/pull/64 fix it
