### ISSUE TITLE
doesn't work on Windows 10

### ISSUE THREAD

**Issue by soapdog** [sveltejs/template-webpack#9]
The out-of-box experience for this template, as described on the readme, doesn't work on Windows 10 machines. I suspect it is a _building paths_ issue as can be seen on the capture 
https://guides.github.com/features/mastering-markdown/below:

```                                                                                                                                                                                    ERROR in ./src/App.html
Module not found: Error: Can't resolve 'C:UserssoapdogprogssbcpatchlandsrcApp.svelte.css' in 'C:\Users\soapdog\prog\ssbc\patchland\src'
@ ./src/App.html 80:0-65
@ ./src/main.js
@ multi ./src/main.js 
```

**Comment by fergusrm** [comment]
This seems to have fixed the issue: https://github.com/sveltejs/svelte-loader/pull/64.  Updating svelte-loader to 2.11.0 got things working for me, so it looks like maybe the template needs to update the dependency version.

**Comment by JordanShurmer** [comment]
PR #11 will fix this. See [this comment](https://github.com/sveltejs/template-webpack/issues/10#issuecomment-430689848) for more info

**Comment by gavinr** [comment]
This is working in windows 10 for me - can we close this issue?
